### PR TITLE
Passing options to the JVM

### PR DESCRIPTION
**Pull request by danielegozzi**
I need to set explicitly the -Xmx parameter for the JVM to run inside an LXC container, because by default it is picking up the amount of memory installed in the host system (via /proc filesystem), thus exceeding the memory limit set for the container.
With this patch I am able to set whatever options the JVM needs with the JAVA_OPTS environment variable, which is honored also by Jruby and by most Java software init/wrapper scripts.

### CODE REVIEW

**Comment by cjohansen** [comment]
Mind rebasing against current master?

**Comment by danielegozzi** [comment]
I do not mind at all. I am currently on holiday. ETA ~ 1-2 weeks. Thanks
for your interest.
Il 03/ago/2014 17:02 "Christian Johansen" notifications@github.com ha
scritto:

**Comment by danielegozzi** [comment]
I rebased my commits on your master. Now only 3a705050687421a88135bd7ba8e428655298793a has some significance (it's about the usage of $JAVA_OPTS in the command line of slave java processes).

**Comment by cjohansen** [comment]
Sure? It is still unpullable in the GitHub UI, and I see no updates on the commits.

**Comment by danielegozzi** [comment]
I must have mangled something with my previous push. A couple of new commits should be visible now.
My most recent commit overhauls the usage of IO.popen as to avoid executing command shells. This was needed to avoid command injections in the JAVA_OPTS environment variable, but I am mostly sure that command injections were possible even before through other parameters such as input filenames.

**Comment by cjohansen** [comment]
Thanks! 1.2.0 is out

**Pull request merged**
